var searchData=
[
  ['latencytest',['LatencyTest',['../classOVR_1_1Util_1_1LatencyTest.html',1,'OVR::Util']]],
  ['latencytest2',['LatencyTest2',['../classOVR_1_1Util_1_1LatencyTest2.html',1,'OVR::Util']]],
  ['latencytestbutton',['LatencyTestButton',['../structOVR_1_1LatencyTestButton.html',1,'OVR']]],
  ['latencytestbuttonmessage',['LatencyTestButtonMessage',['../namespaceOVR.html#structOVR_1_1LatencyTestButtonMessage',1,'OVR']]],
  ['latencytestcalibrateimpl',['LatencyTestCalibrateImpl',['../structOVR_1_1LatencyTestCalibrateImpl.html',1,'OVR']]],
  ['latencytestcolordetected',['LatencyTestColorDetected',['../structOVR_1_1LatencyTestColorDetected.html',1,'OVR']]],
  ['latencytestcolordetectedmessage',['LatencyTestColorDetectedMessage',['../namespaceOVR.html#structOVR_1_1LatencyTestColorDetectedMessage',1,'OVR']]],
  ['latencytestconfiguration',['LatencyTestConfiguration',['../structOVR_1_1LatencyTestConfiguration.html',1,'OVR']]],
  ['latencytestconfigurationimpl',['LatencyTestConfigurationImpl',['../structOVR_1_1LatencyTestConfigurationImpl.html',1,'OVR']]],
  ['latencytestdevice',['LatencyTestDevice',['../classOVR_1_1LatencyTestDevice.html',1,'OVR']]],
  ['latencytestdevicecreatedesc',['LatencyTestDeviceCreateDesc',['../classOVR_1_1LatencyTestDeviceCreateDesc.html',1,'OVR']]],
  ['latencytestdevicefactory',['LatencyTestDeviceFactory',['../classOVR_1_1LatencyTestDeviceFactory.html',1,'OVR']]],
  ['latencytestdeviceimpl',['LatencyTestDeviceImpl',['../classOVR_1_1LatencyTestDeviceImpl.html',1,'OVR']]],
  ['latencytestdisplay',['LatencyTestDisplay',['../structOVR_1_1LatencyTestDisplay.html',1,'OVR']]],
  ['latencytestdisplayimpl',['LatencyTestDisplayImpl',['../structOVR_1_1LatencyTestDisplayImpl.html',1,'OVR']]],
  ['latencytesthandler',['LatencyTestHandler',['../classOVR_1_1Util_1_1LatencyTest_1_1LatencyTestHandler.html',1,'OVR::Util::LatencyTest']]],
  ['latencytestsample',['LatencyTestSample',['../namespaceOVR.html#structOVR_1_1LatencyTestSample',1,'OVR']]],
  ['latencytestsamples',['LatencyTestSamples',['../structOVR_1_1LatencyTestSamples.html',1,'OVR']]],
  ['latencytestsamplesmessage',['LatencyTestSamplesMessage',['../namespaceOVR.html#structOVR_1_1LatencyTestSamplesMessage',1,'OVR']]],
  ['latencyteststarted',['LatencyTestStarted',['../structOVR_1_1LatencyTestStarted.html',1,'OVR']]],
  ['latencyteststartedmessage',['LatencyTestStartedMessage',['../namespaceOVR.html#structOVR_1_1LatencyTestStartedMessage',1,'OVR']]],
  ['latencyteststarttestimpl',['LatencyTestStartTestImpl',['../structOVR_1_1LatencyTestStartTestImpl.html',1,'OVR']]],
  ['latencyvertex',['LatencyVertex',['../structOVR_1_1CAPI_1_1GL_1_1LatencyVertex.html',1,'OVR::CAPI::GL']]],
  ['lensconfig',['LensConfig',['../structOVR_1_1LensConfig.html',1,'OVR']]],
  ['lensconfigstored_5fcatmullrom10version1',['LensConfigStored_CatmullRom10Version1',['../namespaceOVR.html#structOVR_1_1LensConfigStored__CatmullRom10Version1',1,'OVR']]],
  ['lensdistortionimpl',['LensDistortionImpl',['../structOVR_1_1LensDistortionImpl.html',1,'OVR']]],
  ['lensdistortionreport',['LensDistortionReport',['../structOVR_1_1LensDistortionReport.html',1,'OVR']]],
  ['list',['List',['../classOVR_1_1List.html',1,'OVR']]],
  ['list_3c_20notifyevent_20_3e',['List&lt; NotifyEvent &gt;',['../classOVR_1_1List.html',1,'OVR']]],
  ['list_3c_20ovr_3a_3acapi_3a_3ahmdstate_20_3e',['List&lt; OVR::CAPI::HMDState &gt;',['../classOVR_1_1List.html',1,'OVR']]],
  ['list_3c_20ovr_3a_3adevicecreatedesc_20_3e',['List&lt; OVR::DeviceCreateDesc &gt;',['../classOVR_1_1List.html',1,'OVR']]],
  ['list_3c_20ovr_3a_3adevicefactory_20_3e',['List&lt; OVR::DeviceFactory &gt;',['../classOVR_1_1List.html',1,'OVR']]],
  ['list_3c_20ovr_3a_3ajson_20_3e',['List&lt; OVR::JSON &gt;',['../classOVR_1_1List.html',1,'OVR']]],
  ['list_3c_20ovr_3a_3autil_3a_3alatencytest_3a_3ameasurementresult_20_3e',['List&lt; OVR::Util::LatencyTest::MeasurementResult &gt;',['../classOVR_1_1List.html',1,'OVR']]],
  ['listnode',['ListNode',['../structOVR_1_1ListNode.html',1,'OVR']]],
  ['listnode_2e_5f_5funnamed_5f_5f',['ListNode.__unnamed__',['../namespaceOVR.html#unionOVR_1_1ListNode_8____unnamed____',1,'OVR::ListNode.__unnamed__'],['../namespaceOVR.html#unionOVR_1_1ListNode_8____unnamed____',1,'OVR::ListNode.__unnamed__']]],
  ['listnode_3c_20b_20_3e',['ListNode&lt; B &gt;',['../structOVR_1_1ListNode.html',1,'OVR']]],
  ['listnode_3c_20devicecreatedesc_20_3e',['ListNode&lt; DeviceCreateDesc &gt;',['../structOVR_1_1ListNode.html',1,'OVR']]],
  ['listnode_3c_20devicefactory_20_3e',['ListNode&lt; DeviceFactory &gt;',['../structOVR_1_1ListNode.html',1,'OVR']]],
  ['listnode_3c_20hmdstate_20_3e',['ListNode&lt; HMDState &gt;',['../structOVR_1_1ListNode.html',1,'OVR']]],
  ['listnode_3c_20json_20_3e',['ListNode&lt; JSON &gt;',['../structOVR_1_1ListNode.html',1,'OVR']]],
  ['listnode_3c_20measurementresult_20_3e',['ListNode&lt; MeasurementResult &gt;',['../structOVR_1_1ListNode.html',1,'OVR']]],
  ['listnode_3c_20notifyevent_20_3e',['ListNode&lt; NotifyEvent &gt;',['../structOVR_1_1ListNode.html',1,'OVR']]],
  ['listnode_3c_20ovr_3a_3acapi_3a_3ahmdstate_20_3e',['ListNode&lt; OVR::CAPI::HMDState &gt;',['../structOVR_1_1ListNode.html',1,'OVR']]],
  ['listnode_3c_20ovr_3a_3adevicecreatedesc_20_3e',['ListNode&lt; OVR::DeviceCreateDesc &gt;',['../structOVR_1_1ListNode.html',1,'OVR']]],
  ['listnode_3c_20ovr_3a_3adevicefactory_20_3e',['ListNode&lt; OVR::DeviceFactory &gt;',['../structOVR_1_1ListNode.html',1,'OVR']]],
  ['listnode_3c_20ovr_3a_3ajson_20_3e',['ListNode&lt; OVR::JSON &gt;',['../structOVR_1_1ListNode.html',1,'OVR']]],
  ['listnode_3c_20ovr_3a_3autil_3a_3alatencytest_3a_3ameasurementresult_20_3e',['ListNode&lt; OVR::Util::LatencyTest::MeasurementResult &gt;',['../structOVR_1_1ListNode.html',1,'OVR']]],
  ['lock',['Lock',['../classOVR_1_1Lock.html',1,'OVR']]],
  ['locker',['Locker',['../classOVR_1_1Mutex_1_1Locker.html',1,'OVR::Mutex']]],
  ['locker',['Locker',['../classOVR_1_1Lock_1_1Locker.html',1,'OVR::Lock']]],
  ['locklessstate',['LocklessState',['../structOVR_1_1SensorFusion_1_1LocklessState.html',1,'OVR::SensorFusion']]],
  ['locklessupdater',['LocklessUpdater',['../classOVR_1_1LocklessUpdater.html',1,'OVR']]],
  ['locklessupdater_3c_20ovr_3a_3acapi_3a_3aframetimemanager_3a_3atiming_20_3e',['LocklessUpdater&lt; OVR::CAPI::FrameTimeManager::Timing &gt;',['../classOVR_1_1LocklessUpdater.html',1,'OVR']]],
  ['locklessupdater_3c_20ovr_3a_3asensorfusion_3a_3alocklessstate_20_3e',['LocklessUpdater&lt; OVR::SensorFusion::LocklessState &gt;',['../classOVR_1_1LocklessUpdater.html',1,'OVR']]],
  ['locklessupdater_3c_20ovr_3a_3autil_3a_3aframetimerecordset_20_3e',['LocklessUpdater&lt; OVR::Util::FrameTimeRecordSet &gt;',['../classOVR_1_1LocklessUpdater.html',1,'OVR']]],
  ['log',['Log',['../classOVR_1_1Log.html',1,'OVR']]]
];
