var searchData=
[
  ['ldbl_5fdig',['LDBL_DIG',['../OVR__Linux__HMDDevice_8cpp.html',1,'OVR_Linux_HMDDevice.cpp']]],
  ['ldbl_5fepsilon',['LDBL_EPSILON',['../OVR__Linux__HMDDevice_8cpp.html',1,'OVR_Linux_HMDDevice.cpp']]],
  ['ldbl_5fmant_5fdig',['LDBL_MANT_DIG',['../OVR__Linux__HMDDevice_8cpp.html',1,'OVR_Linux_HMDDevice.cpp']]],
  ['ldbl_5fmax',['LDBL_MAX',['../OVR__Linux__HMDDevice_8cpp.html',1,'OVR_Linux_HMDDevice.cpp']]],
  ['ldbl_5fmax_5f10_5fexp',['LDBL_MAX_10_EXP',['../OVR__Linux__HMDDevice_8cpp.html',1,'OVR_Linux_HMDDevice.cpp']]],
  ['ldbl_5fmax_5fexp',['LDBL_MAX_EXP',['../OVR__Linux__HMDDevice_8cpp.html',1,'OVR_Linux_HMDDevice.cpp']]],
  ['ldbl_5fmin',['LDBL_MIN',['../OVR__Linux__HMDDevice_8cpp.html',1,'OVR_Linux_HMDDevice.cpp']]],
  ['ldbl_5fmin_5f10_5fexp',['LDBL_MIN_10_EXP',['../OVR__Linux__HMDDevice_8cpp.html',1,'OVR_Linux_HMDDevice.cpp']]],
  ['ldbl_5fmin_5fexp',['LDBL_MIN_EXP',['../OVR__Linux__HMDDevice_8cpp.html',1,'OVR_Linux_HMDDevice.cpp']]],
  ['le16toh',['le16toh',['../OVR__Types_8h.html',1,'OVR_Types.h']]],
  ['le32toh',['le32toh',['../OVR__Types_8h.html',1,'OVR_Types.h']]],
  ['le64toh',['le64toh',['../OVR__Types_8h.html',1,'OVR_Types.h']]],
  ['led1',['LED1',['../launchpad_8h.html#a8aa85ae9867fabf70ec72cd3bf6fb6b9',1,'launchpad.h']]],
  ['led2',['LED2',['../launchpad_8h.html#ad09fe5bf321b9a2de26bd5e5b9af6424',1,'launchpad.h']]],
  ['link_5fmax',['LINK_MAX',['../OVR__Linux__HMDDevice_8cpp.html',1,'OVR_Linux_HMDDevice.cpp']]],
  ['little_5fendian',['LITTLE_ENDIAN',['../OVR__Types_8h.html',1,'OVR_Types.h']]],
  ['login_5fname_5fmax',['LOGIN_NAME_MAX',['../OVR__Linux__HMDDevice_8cpp.html',1,'OVR_Linux_HMDDevice.cpp']]]
];
